### ISSUE TITLE
pcie link_up failed

### ISSUE THREAD

**Issue by bournejason** [fpgasystems/davos#7]
Hi
I used latest project and successfully generated bit file for vcu118, but after loading the bit, I saw LED[1] and LED[2] ON, while LED[3] & LED[4] & LED[5] are blinking.
According to the top rtl
![code](https://user-images.githubusercontent.com/4476789/96396284-6f7e2900-11f9-11eb-89a3-5a0ea56e8eed.png)

It seems pcie is not linked up (LED[0] OFF), while rx_aligned_led is low (LED[6] OFF).
Based on my configuration, I only used 10G network, so rx_aligned_led can be negelected.
I didn't change anything in the source code, and the pcie connector was good too. Any clues why it didn't link up?
Thanks!

**Comment by klajdZyla** [comment]
I have the same problem. Did you find a solution?
